# Generated by Django 5.1.2 on 2024-11-07 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_users_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
