# Generated by Django 5.1.2 on 2024-11-09 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_cardbutton_alter_product_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CardButton',
        ),
    ]
