# Generated by Django 5.1.2 on 2024-11-21 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_delete_cardbutton'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='cost',
            new_name='price',
        ),
    ]
