# Generated by Django 5.1.2 on 2024-11-21 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_cost_product_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='title',
            new_name='name',
        ),
    ]
